### ISSUE TITLE
Client cant connect to server

### ISSUE THREAD

**Issue by vujonycoder** [Seyz123/node-mcpe-client#1]
Client cant connect (i see error in console)
![image](https://user-images.githubusercontent.com/62576358/84556674-b1b7cb00-ad2c-11ea-892f-36e4b5e4eb0e.png)

But i add if
![image](https://user-images.githubusercontent.com/62576358/84556654-7fa66900-ad2c-11ea-8441-319a7151b265.png)
My bot connect to server, but on server in debug mode i see error
`Ignored unconnected packet from 123.456.789.123 12345 due to session already opened (0x9)`

I test on pocketmine 1.14.60

**Comment by Seyz123** [comment]
Hello! That project is a WIP therefore it is not finished / usable.

**Comment by vujonycoder** [comment]
Oh, thank.
